name: Api testing by using Postman-newman
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Make Directory for results
        run: mkdir -p testResults
      - name: Run POSTMAN collection
        run: |
          newman run "store.collection.json" -r htmlextra --reporter-htmlextra-export testResults/index.html
      - name: Output the run Details
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: RunReport
          path: ./testResults
      - name: Deploy to pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: ./testResults